project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  twitter-card: true
  open-graph: true
  site-url: "https://gandenberger.org"
  image: "profile.jpg"
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto
resources:
  - CNAME
comments:
  hypothesis: true